import assert from 'node:assert/strict';
import * as THREE from '../vendor/three.module.js';
globalThis.window={addEventListener(){}};
globalThis.indexedDB={open(){return {};}};
const {paintAuthored}=await import('../authored-viewer.js');
const original=new THREE.MeshStandardMaterial({color:'#665544',roughness:.72,metalness:.21});
original.map=new THREE.Texture();original.map.repeat.set(3,4);original.normalMap=new THREE.Texture();original.roughnessMap=new THREE.Texture();
const m=original.clone();m.userData.vreelOriginal={map:original.map,color:original.color.clone()};
const viewer={createTexture:async()=>new THREE.Texture()};
await paintAuthored(m,{id:'color',color:'#112244'},viewer);
assert.equal(m.color.getHexString(),'112244');assert.equal(m.map,null);
assert.equal(m.normalMap,original.normalMap);assert.equal(m.roughnessMap,original.roughnessMap);assert.equal(m.roughness,.72);assert.equal(m.metalness,.21);
await paintAuthored(m,{id:'texture',image:'blob:test'},viewer);assert.deepEqual(m.map.repeat.toArray(),[3,4]);assert.equal(m.color.getHexString(),'ffffff');
await paintAuthored(m,{id:'original',original:true},viewer);assert.equal(m.map,original.map);assert.equal(m.color.getHexString(),'665544');
console.log('PASS: authored color, texture UV transforms, fixed PBR maps and original restoration.');
const {updateAuthoredDimensions}=await import('../authored-viewer.js');
globalThis.document={querySelectorAll:()=>[]};
const guides=[{part:'product',axis:'G',value:.6},{part:'product',axis:'D',value:.5},{part:'product',axis:'Y',value:1}];
const config={draft:{features:{dimensions:true},unit:'cm',width:999,depth:999,height:999}};
updateAuthoredDimensions(config,{},guides);assert.deepEqual(guides.map(g=>g.label),['G 999 cm','D 999 cm','Y 999 cm']);
delete config.draft.width;delete config.draft.depth;delete config.draft.height;
config.draft.unit='mm';updateAuthoredDimensions(config,{},guides);assert.equal(guides[0].label,'G 600 mm');
delete config.draft.width;delete config.draft.depth;delete config.draft.height;config.draft.unit='m';updateAuthoredDimensions(config,{},guides);assert.equal(guides[0].label,'G 0.6 m');
console.log('PASS: manual dimensions take precedence; empty dimensions use geometry with unit conversion.');

config.draft.width=75;config.draft.unit='cm';updateAuthoredDimensions(config,{},guides);assert.deepEqual(guides.map(g=>g.label),['G 75 cm','D 50 cm','Y 100 cm']);
const {prepareAuthoredComponents}=await import('../authored-viewer.js');
const dom={createElement(){return {dataset:{},append(){}};},querySelector(){return {append(){}};}};
globalThis.document=dom;
const root=new THREE.Group();
for(let i=0;i<2;i++){const node=new THREE.Group();node.userData={sourceName:`P_${i}`,sourceNodeIndex:i};root.add(node);}
const componentConfig={draft:{componentGroups:[{id:'size',name:'Size',defaultId:'small',options:[{id:'large',label:'100 cm',nodeId:'node-0'},{id:'small',label:'65 cm',nodeId:'node-1'}]}]}};
let change,changeCount=0;
const buttons=[{dataset:{variant:'large'},classList:{toggle(){}}},{dataset:{variant:'small'},classList:{toggle(){}}}],summary={};
const componentViewer={model:{root},reframe(){},requestUpdate(){}};
const reset=await prepareAuthoredComponents(componentConfig,componentViewer,(_name,_options,_initial,handler)=>{change=handler;return {querySelectorAll:()=>buttons,querySelector:()=>summary};},()=>changeCount++);
assert(!root.children[0].visible);assert(root.children[1].visible);assert.equal(componentConfig.componentChoices.size.value,'65 cm');
change('large');assert(root.children[0].visible);assert(!root.children[1].visible);assert.equal(componentConfig.componentChoices.size.value,'100 cm');
reset();assert(!root.children[0].visible);assert(root.children[1].visible);assert.equal(componentConfig.componentChoices.size.value,'65 cm');assert.equal(changeCount,2);
console.log('PASS: public component defaults, independent selection labels, reset to default.');
