import assert from 'node:assert/strict';
import * as THREE from '../vendor/three.module.js';
import {collectComponents,componentMap,applyComponentSelection,componentErrors,alignAlternative,mountAlternatives,materialTargetId} from '../component-options.js';
const root=new THREE.Group();
function part(name,id,width=1){const group=new THREE.Group();group.name=name;group.userData={sourceName:name,sourceNodeIndex:id};group.add(new THREE.Mesh(new THREE.BoxGeometry(width,1,1),new THREE.MeshStandardMaterial()));root.add(group);return group;}
const a=part('P_Cabinet',0,1),b=part('P_Cabinet',1,.65),fixed=part('P_Tall',2),nested=part('P_Doors',3);
a.add(nested);
// Autogenerated mesh names and lower meshes must not become selectable groups.
a.children[0].name='P_Cabinet';
let available=collectComponents(root);assert.equal(available.length,4);assert.equal(available.find(c=>c.id==='node-3').path,'P_Cabinet / P_Doors');
const options=[{id:'large',nodeId:'node-0',label:'100 cm'},{id:'small',nodeId:'node-1',label:'65 cm'}];
const group={id:'size',name:'Size',defaultId:'small',options};
const draft={componentGroups:[group],componentAssets:[]};
const nodes=componentMap(root);applyComponentSelection(nodes,draft.componentGroups);assert.equal(a.visible,false);assert.equal(b.visible,true);assert.equal(fixed.visible,true);assert.equal(nested.visible,true);
applyComponentSelection(nodes,draft.componentGroups,new Map([['size','large']]));assert(a.visible);assert(!b.visible);
assert.deepEqual(componentErrors(draft,available),[]);
assert(componentErrors({...draft,componentGroups:[{...group,defaultId:'missing'}]},available).some(e=>e.includes('varsayılan')));
assert(componentErrors({...draft,componentGroups:[group,{...group,id:'duplicate'}]},available).some(e=>e.includes('yalnızca')));
assert(componentErrors({...draft,componentGroups:[group,{id:'doors',name:'Doors',defaultId:'d',options:[{id:'d',nodeId:'node-3',label:'Door'}]}]},available).some(e=>e.includes('İç içe')));
const external=new THREE.Group();external.add(new THREE.Mesh(new THREE.BoxGeometry(.85,1,1),new THREE.MeshStandardMaterial()));external.position.set(100,10,-20);
root.position.set(4,2,3);root.rotation.y=.3;root.scale.setScalar(1.3);
const wrapper=alignAlternative(external,b,root);
const center=x=>new THREE.Box3().setFromObject(x).getCenter(new THREE.Vector3());assert(center(external).distanceTo(center(b))<1e-8);
assert.equal(external.scale.x,1);root.remove(wrapper);
const empty=new THREE.Group();assert.throws(()=>alignAlternative(empty,b,root),/geometri/);
const extOption={id:'external',label:'85 cm',assetId:'file',referenceId:'node-0'};draft.componentGroups[0].options.push(extOption);draft.componentAssets.push({id:'file'});
assert.deepEqual(componentErrors(draft,available),[]);
assert(componentErrors({...draft,componentAssets:[]},available).some(e=>e.includes('dosya eksik')));
const ext=new THREE.Group();ext.name='P_External';ext.userData.sourceNodeIndex=0;ext.add(new THREE.Mesh(new THREE.BoxGeometry(.85,1,1),new THREE.MeshStandardMaterial()));
const viewer={model:{root},loadAdditionalModel:async()=>ext};
const mounted=await mountAlternatives(viewer,draft,()=> 'blob:test');
assert(mounted.has('asset-file'));assert.equal(collectComponents(root).length,4);
const mesh=ext.children[0];assert.equal(materialTargetId(mesh,999,0),'asset-file-mesh-0-slot-0');assert.equal(materialTargetId(b.children[0],1,0),'mesh-1-slot-0');
applyComponentSelection(mounted,draft.componentGroups,new Map([['size','external']]));assert(!a.visible&&!b.visible);assert(mounted.get('asset-file').visible);assert(fixed.visible);
// Visible geometry contains only the selected alternative and fixed parts.
const visible=[];root.traverseVisible(n=>{if(n.isMesh)visible.push(n);});assert(!visible.includes(a.children[0]));assert(visible.includes(mesh));
const snapshot=structuredClone(draft);draft.componentGroups[0].options[0].label='Changed';assert.equal(snapshot.componentGroups[0].options[0].label,'100 cm');
console.log('PASS: P_ hierarchy/duplicate names, exclusive defaults and selection, fixed parts, nested/duplicate validation, external alignment under transforms, independent material IDs, visible-only geometry, snapshot isolation.');
